apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventflow
  template:
    metadata:
      labels:
        app: eventflow
    spec:
      containers:
        - name: eventflow
          image: ghcr.io/zakaria-source/eventflow:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: eventflow-config
            - secretRef:
                name: eventflow-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {cpu: 500m, memory: 512Mi}
